### ISSUE TITLE
ERROR : Error: [$parse:lexerr] Lexer Error: Unexpected next character  at columns 1-1

### ISSUE THREAD

**Issue by jmcollin78** [ghiden/angucomplete-alt#283]
Hello,

Since a few days I've got an error on angucomplete-alt search.
The error is:
<code>
Error: [$parse:lexerr] Lexer Error: Unexpected next character  at columns 1-1 [\] in expression [{\'angucomplete-selected-row\': $index == currentIndex}].
http://errors.angularjs.org/1.4.7/$parse/lexerr?p0=Unexpected%20nextharacter%20&p1=s%201-1%20%5B%5C%5D&p2=%7B%5C'angucomplete-selected-row%5C'%3A%20%24index%20%3D%3D%currentIndex%7D
    at REGEX_STRING_REGEXP (http://localhost:3000/system/public/lib/angular/angular.js:68:12)
    at Lexer.throwError (http://localhost:3000/system/public/lib/angular/angular.js:12700:11)
    at Lexer.lex (http://localhost:3000/system/public/lib/angular/angular.js:12659:16)
    at Object.AST.ast (http://localhost:3000/system/public/lib/angular/angular.js:12822:30)
    at Object.ASTCompiler.compile (http://localhost:3000/system/public/lib/angular/angular.js:13276:31)
    at Parser.parse (http://localhost:3000/system/public/lib/angular/angular.js:14146:29)
    at $parse (http://localhost:3000/system/public/lib/angular/angular.js:14248:39)
    at Scope.parent.$get.Scope.$watch (http://localhost:3000/system/public/lib/angular/angular.js:15412:19)
    at $animate.link (http://localhost:3000/system/public/lib/angular/angular.js:22605:15)
    at invokeLinkFn (http://localhost:3000/system/public/lib/angular/angular.js:8789:9)
</code>
I'm using the "angucomplete-alt": "1.1.1" and I guess it was correct in 1.1.0 but I'm not sure.

JM.

**Comment by jmcollin78** [comment]
Same problem with 2.0.2

**Comment by jmcollin78** [comment]
Sorry my template was broken...
