### ISSUE TITLE
cannot call setValidity on undefined 

### ISSUE THREAD

**Issue by salluu** [ghiden/angucomplete-alt#298]
Its still not working for me  using  .. i cannot set it required field 
```
<angucomplete-alt id="ex1"
                                  placeholder="type to search model..."
                                  pause="100"
                                  selected-object="selectedModel"
                                  local-data="allProducts"
                                  search-fields="MarketingName,ModelCode"
                                  title-field="ModelCode,MarketingName"
                                  minlength="2"
                                  input-class="form-control"
                                  field-required="true"
                                  auto-match="true"
                                  input-name="user"
                                  initial-value="updateModel" />
```

i get this error
```

TypeError: Cannot read property '$setValidity' of undefined
    at F (http://samsung.dotcomui.local/uk/promotions/js/directives/angucomplete-alt.min.js:2:1775)
    at h (http://samsung.dotcomui.local/uk/promotions/js/directives/angucomplete-alt.min.js:2:8681)
    at http://samsung.dotcomui.local/uk/promotions/scripts/vendor.63784f53.js:20085:44
    at nodeLinkFn (http://samsung.dotcomui.local/uk/promotions/scripts/vendor.63784f53.js:19683:13)
    at http://samsung.dotcomui.local/uk/promotions/scripts/vendor.63784f53.js:19885:13
    at http://samsung.dotcomui.local/uk/promotions/scripts/vendor.63784f53.js:21055:11
    at wrappedCallback (http://samsung.dotcomui.local/uk/promotions/scripts/vendor.63784f53.js:24520:81)
    at wrappedCallback (http://samsung.dotcomui.local/uk/promotions/scripts/vendor.63784f53.js:24520:81)
    at http://samsung.dotcomui.local/uk/promotions/scripts/vendor.63784f53.js:24606:26
    at Scope.$eval (http://samsung.dotcomui.local/uk/promotions/scripts/vendor.63784f53.js:25630:28) <angucomplete-alt id="ex1" placeholder="type to search model..." pause="100" selected-object="selectedModel" local-data="allProducts" search-fields="MarketingName,ModelCode" title-field="ModelCode,MarketingName" minlength="2" input-class="form-control" field-required="true" auto-match="true" input-name="user" initial-value="updateModel" class="ng-isolate-scope">

please help thanks
```

**Comment by salluu** [comment]
i am using latest version  and #287 is still not resolved

**Comment by ghiden** [comment]
Are you still having this issue?

**Comment by salluu** [comment]
yes its not i am not using  field-required because of it

**Comment by unlimited071** [comment]
I'm also having this issue. I've created the following Plunker [http://plnkr.co/edit/4Zwo4gLmVeHa46tBot81](url) that reproduces the error.

**Comment by unlimited071** [comment]
Ok, I've figured out my issue and I'm leaving it here for anyone that may need it in the future. In my case I was using a custom template but the template did not set the field name for the input. Setting the input name property in the template fixed the issue. [Link to Plunker](http://plnkr.co/edit/4Zwo4gLmVeHa46tBot81)
